{
 "title": "POS - Logs",
 "tags": [
  "pos",
  "logs",
  "loki",
  "security"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Web Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"webapp\"}"
    }
   ]
  },
  {
   "title": "Failed Logins Over Time (LOGIN_FAILED / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"webapp\"} |= \"LOGIN_FAILED\" [1m]))",
     "legendFormat": "Failed Attempts / min"
    }
   ]
  },
  {
   "title": "Top HTTP Status Codes (Nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"nginx\"} [1m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Nginx Access & Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"nginx\"}"
    }
   ]
  }
 ]
}